run:
  #modules-download-mode: readonly
linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocognit:
    min-complexity: 20
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  depguard:
    list-type: whitelist
    packages:
      - github.com/stretchr/testify/assert
      - github.com/nikandfor/tlog
      - github.com/pkg/errors
  misspell:
  lll:
    line-length: 170
  goimports:
    local-prefixes: github.com/nikandfor/errors
  prealloc:
    simple: true
    for-loops: true
  gocritic:
    enabled-tags:
      - experimental
      - performance
      - style
    disabled-checks:
      - appendAssign
      - builtinShadow
      - commentedOutCode
      - unnamedResult
      - whyNoLint
      - yodaStyleExpr

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - gomnd
    - nakedret
    - nlreturn
    - testpackage
    - unparam
    - wsl
