language: go

env:
  global:
    - GO111MODULE=on

os:
  - linux
  - osx
  - windows

arch:
  - amd64

go:
  - "1.15"
  - "1.14"
  - "1.13"

jobs:
  include:
    - os: linux
      go: "1.15"
      arch: arm64

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - test "$TRAVIS_OS_NAME" = linux && test "$TRAVIS_CPU_ARCH" = amd64 && test "$TRAVIS_GO_VERSION" = "1.13" && export CODECOV_UPLOAD=yes
  - test $CODECOV_UPLOAD = "yes" && bash <(curl -s https://codecov.io/bash)
